# Generated by Django 3.0.3 on 2020-02-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Peak',
        ),
    ]
