# Generated by Django 3.0.3 on 2020-02-06 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_app', '0002_auto_20200205_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='altitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='peak',
            name='lat',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='peak',
            name='lon',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
